### ISSUE TITLE
Error with \pdf@elapsedtime (LuaTeX) : math.floor or related is required

### ISSUE THREAD

**Issue by FOCCOF** [ho-tex/pdftexcmds#4]
Problem : \pdf@elapsedtime defined for LuaTeX (in pdftexcmds.lua) says at the end :+1: 

tex.write(string.format("%d", val))

while it should probably say :+1: 

tex.write(string.format("%d", math.floor(val)))

Because `val' is not an integer but a float, which has to be truncated before printing.

------- MINIMAL EXAMPLE FOR   lualatex    -----------------------------------
\documentclass {minimal}
\usepackage {pdftexcmds}

\begin{document}\makeatletter

\showthe\pdf@elapsedtime

\end{document}
------------------------------------------------------------------------------------
-------------- ERROR --------------------------------------------------------------------
\showthe\pdf@elapsedtime

\pdf@elapsedtime ->\numexpr \pdftexcmds@directlua {oberdiek.pdftexcmds.elapsedtime()}\relax 
{\directlua}
C:/texmf/scripts/pdftexcmds/pdftexcmds.lua:291: bad argument #2 to 'format' (number has no integer representation)
stack traceback:
	[C]: in function 'string.format'
	C:/texmf/scripts/pdftexcmds/pdftexcmds.lua:291: in field 'elapsedtime'
	[\directlua]:1: in main chunk.
\pdf@elapsedtime ...diek.pdftexcmds.elapsedtime()}
                                                  \relax

**Comment by davidcarlisle** [comment]
Thanks for the report, the test file was Ok as recently as texlive 2018. I assume this is Lua 5.3 introducing the integer type that has broken it, we'll fix.

**Comment by u-fischer** [comment]
@davidcarlisle  I added the math.floor and will upload to ctan.

**Comment by josephwright** [comment]
Funny, we already had this in `l3luatex`!

**Comment by u-fischer** [comment]
fix has been sent to ctan.
