### ISSUE TITLE
Version 2020-06-27 v0.33 Error?

### ISSUE THREAD

**Issue by eplain** [ho-tex/pdftexcmds#6]
Compiling with MiKTeX  using eplain  load package {graphicsx} I receive the error:
(C:\Users\jlewis\AppData\Roaming\MiKTeX\2.9\tex/generic/pdftexcmds\pdftexcmds.s
ty
! Missing = inserted for \ifnum.
<to be read again>
                   -
<argument> 2020-
                06-27 v0.33 Utility functions of pdfTeX for LuaTeX (HO)
\@parse@version #1/#2/#3#4#5\@nil ->#1
                                      #2#3#4
\@ifl@t@r ...andafter \@parse@version #1//00\@nil
                                                  <\expandafter \@parse@vers...

\eplain@pr@videpackage ...fl@t@r {#2}\usepkg@date

<return> compilation completes ssuccessfuly.
                                                  {}{\message {Warning: you ...

\x #1#2[#3]->\endgroup #2[{#3}]
                               \ifx #1\@undefined \xdef #1{#3}\fi \ifx #1\re...
l.108 ...lity functions of pdfTeX for LuaTeX (HO)]
                                                  %

**Comment by u-fischer** [comment]
please provide a complete example that can be used for tests.

**Comment by u-fischer** [comment]
you are probably using an outdated version of eplain.tex, which can't handle dates in ISO format. The current eplain in miktex has version 3.11: 

     %%   version = "3.11",
     %%   date = "Sat Jul  4 08:41:11 PDT 2020",
